# Assignment For Numpy 01

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# 1. Import the numpy package under the name np
import numpy as np

In [7]:
np.__version__

'1.18.1'

In [6]:
!pip install --upgrade --user numpy

Requirement already up-to-date: numpy in c:\users\hassan amin\appdata\roaming\python\python37\site-packages (1.19.4)
Note: you may need to restart the kernel to use updated packages.


In [8]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#1 1d arrays
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#2 2d arrays
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
#3 3d arrays
c = np.arange(32).reshape(2,4,4)  
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [27]:
#4 Number of array dimensions
x = np.array([1, 2, 3])
x.ndim

1

In [28]:
#5 Element Size
x = np.array([1,2,3], dtype=np.float64)
x.itemsize

8

In [29]:
#6 Data Type
x = np.array ([1,2,3])
print(x.dtype)

int32


In [30]:
#7 Size
x = np.array([(1,2,3,4,5,6)])
print(x.size)

6


In [32]:
#8 Shape
x = np.array([(1,2,3,4,5,6)])
print(x.shape)

(1, 6)


In [36]:
#9 Slicing
x = np.array([(1,2,3,4),(3,4,5,6)])
print(x[0:,3])

[4 6]


In [37]:
#10 Boolean
boolean_array = np.array([1, 0.5, 0, None], dtype=bool)
print(boolean_array)

[ True  True False False]


In [43]:
#11 Item Size
x = np.array([(1,2,3)], dtype=np.complex128)
print(x.itemsize)

16


In [44]:
#12
a = b*2
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [45]:
#13
c = a+b
c

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [46]:
#14
c>47

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [57]:
#15
a[2]

array([16, 18, 20, 22])

In [58]:
#16
np.sqrt(a)

array([[0.        , 1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162, 3.74165739],
       [4.        , 4.24264069, 4.47213595, 4.69041576],
       [4.89897949, 5.09901951, 5.29150262, 5.47722558]])

In [59]:
#17
np.power(b,2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [60]:
#18
np.exp(a)

array([[1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06],
       [8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09],
       [2.64891221e+10, 1.95729609e+11, 1.44625706e+12, 1.06864746e+13]])

In [61]:
#19
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [62]:
#20
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [63]:
#21
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [64]:
#22
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [65]:
#23
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [66]:
#24
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [67]:
#25
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [69]:
#26
e = np.arange(10)
e[e%2 == 0] = 2
e

array([2, 1, 2, 3, 2, 5, 2, 7, 2, 9])

In [71]:
#27
f = np.arange(10)
g= np.where(f % 2 == 1, -1, f)
print(f)
g

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [76]:
#28
g = np.arange(32)
h = np.reshape(g, (-1, 2))
h

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [77]:
#29
g = np.arange(32)
h = np.reshape(g, (2, -1))
h

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [79]:
#30
b[(b >= 6) & (b <= 11)]

array([ 6,  7,  8,  9, 10, 11])

In [80]:
#31
index = np.where(np.logical_and(b>=6, b<=11))
index

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [81]:
#32
np.where(a!=b)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [86]:
#33
arr = np.arange(12).reshape(4,3)
arr[:,[1,0,2]]

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11]])

In [85]:
#34
arr = np.arange(12).reshape(4,3)
arr[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [87]:
#35
np.mean(b)

7.5

In [88]:
#36
np.median(c)

22.5

In [89]:
#37
np.std(a)

9.219544457292887

In [90]:
#38
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [91]:
#39
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [92]:
#40
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.cos(arr))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [93]:
#41
print(np.remainder((arr), 5))

[[1 2 3]
 [4 0 1]]


In [94]:
#42
print(np.reciprocal(arr))

[[1 0 0]
 [0 0 0]]


In [95]:
#43
print(np.ceil(arr))

[[1. 2. 3.]
 [4. 5. 6.]]


In [96]:
#44
print(np.sign(arr))

[[1 1 1]
 [1 1 1]]


In [97]:
#45
print(np.round(arr))

[[1 2 3]
 [4 5 6]]


In [99]:
#46
i = np.random.random(11)
i[i.argmax()]=0
i

array([0.49068181, 0.57214781, 0.40600026, 0.72283525, 0.56817626,
       0.86832755, 0.7252475 , 0.79102295, 0.57064985, 0.        ,
       0.04094272])

In [100]:
#47
i = np.random.random(11)
i.sort()
i

array([0.04612884, 0.20078417, 0.25659674, 0.36960293, 0.40032317,
       0.40980669, 0.53172459, 0.56336839, 0.62789287, 0.6826108 ,
       0.83573244])

In [101]:
#48
c = np.column_stack((a, b))
print(c)

[[ 0  2  4  6  0  1  2  3]
 [ 8 10 12 14  4  5  6  7]
 [16 18 20 22  8  9 10 11]
 [24 26 28 30 12 13 14 15]]


In [102]:
#49
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
Array b:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a > b
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
a >= b
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
a < b
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
a <= b
[[ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [105]:
#50
i = np.linspace(1,4,11)
print(i)

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4. ]
